IMAGE_SIZE = 64
CHANNEL_NUM = 1
NUM_FRAME = 4
INPUT_NEURONS = IMAGE_SIZE * IMAGE_SIZE * CHANNEL_NUM * NUM_FRAME

CLASS_NUM = 3

EPOCH_SIZE = 30
BATCH_SIZE = 100

LEARNING_RATE = 1e-4

GAMMA = 0.1

IMAGES_PATH = 'capture-images/'

CHECKPOINT = './checkpoint/model.ckpt'